listing-4.2: thread-create2.c
	# Crea la carpeta si no existe y compila el ejecutable

	@mkdir -p ../../../bin/capitulo_4/4.2
	gcc thread-create2.c -o ../../../bin/capitulo_4/4.2/thread-create2 -lpthread