listing-5.4: sem_pv.c
	# Crea la carpeta si no existe y compila el ejecutable

	@mkdir -p ../../../bin/capitulo_5/5.4

	# Se usa -pthread para enlazar la libreria pthread
	gcc -pthread sem_pv.c -o ../../../bin/capitulo_5/5.4/sem_pv