listing-5.12: socket-inet.c auto-run.c
	# Crea la carpeta si no existe y compila el ejecutable
	@mkdir -p ../../../bin/capitulo_5/5.12

	# En caso que quiera correr automaticamente el caso de prueba ejecute "auto-run"
	gcc socket-inet.c -o ../../../bin/capitulo_5/5.12/socket-inet
	gcc auto-run.c -o ../../../bin/capitulo_5/5.12/auto-run
