listing-5.8: dup2.c
	# Crea la carpeta si no existe y compila el ejecutable

	@mkdir -p ../../../bin/capitulo_5/5.8

	# Se usa -pthread para enlazar la libreria pthread
	gcc -pthread dup2.c -o ../../../bin/capitulo_5/5.8/dup2