listing-4.11: job-queue2.c
	# Crea la carpeta si no existe y compila el ejecutable

	@mkdir -p ../../../bin/capitulo_4/4.11

	# Se usa -pthread para enlazar la libreria pthread
	gcc -pthread job-queue2.c -o ../../../bin/capitulo_4/4.11/job-queue2