listing-4.3: thread-create2.c
	# Crea la carpeta si no existe y compila el ejecutable

	@mkdir -p ../../../bin/capitulo_4/4.3

	# Necesito arreglar como linkear pthread
	gcc -pthread thread-create2.c -o ../../../bin/capitulo_4/4.3/thread-create2