listing-4.1: thread-create.c
	# Crea la carpeta si no existe y compila el ejecutable

	@mkdir -p ../../../bin/capitulo_4/4.1
	gcc thread-create.c -o ../../../bin/capitulo_4/4.1/thread-create -lpthread