listing-2.3: print-env.c
	gcc -c print-env.c

	# Crea directorio si no existe y asigna el ejecutable
	@mkdir -p ../../../bin/capitulo_2/2.3/

	gcc print-env.o -o ../../../bin/capitulo_2/2.3/print-env

	# Para borrar los archivos .o 
	rm *.o
	