listing-4.15: thread-pid.c
	# Crea la carpeta si no existe y compila el ejecutable

	@mkdir -p ../../../bin/capitulo_4/4.15

	# Se usa -pthread para enlazar la libreria pthread
	gcc -pthread thread-pid.c -o ../../../bin/capitulo_4/4.15/thread-pid