listing-4.6: critical-seccion.c
	# Crea la carpeta si no existe y compila el ejecutable

	@mkdir -p ../../../bin/capitulo_4/4.6
	gcc critical-seccion.c -o ../../../bin/capitulo_4/4.6/critical-seccion -lpthread