listing-3.2: system.c
	gcc -c system.c

	# Crea directorio si no existe y asigna el ejecutable
	@mkdir -p ../../../bin/capitulo_3/3.2/

	gcc system.o -o ../../../bin/capitulo_3/3.2/system

	# Para borrar los archivos .o 
	rm *.o