listing-2.7: test.c
	gcc -c test.c

	# Crea directorio si no existe y asigna el ejecutable
	@mkdir -p ../../../bin/capitulo_2/2.7/

	gcc test.o -o ../../../bin/capitulo_2/2.7/test

	# Para borrar los archivos .o 
	rm *.o
	