listing-4.13: spin-condvar.c
	# Crea la carpeta si no existe y compila el ejecutable

	@mkdir -p ../../../bin/capitulo_4/4.13
	gcc spin-condvar.c -o ../../../bin/capitulo_4/4.13/spin-condvar -lpthread